In [1]:
import pyarrow as pa
import pandas as pd
import numpy as np
import os
import pyarrow.parquet as pq
import fastparquet
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# ler todos os arquivos csv do diret√≥rio e guardar em um objeto
path = '/home/vinicius.vancellote/data/parquet/join/'
all_files = list(filter(lambda x: '.parquet' in x, os.listdir(path)))
all_files_ago = list(filter(lambda x:'G1-2019-08' in x, all_files))
all_files_dez=(list(filter(lambda x:'G1-2019-12' in x, all_files)))
print (all_files_ago)

['G1-2019-08-27.parquet', 'G1-2019-08-12.parquet', 'G1-2019-08-08.parquet', 'G1-2019-08-18.parquet', 'G1-2019-08-31.parquet', 'G1-2019-08-10.parquet', 'G1-2019-08-01.parquet', 'G1-2019-08-03.parquet', 'G1-2019-08-23.parquet', 'G1-2019-08-06.parquet', 'G1-2019-08-28.parquet', 'G1-2019-08-11.parquet', 'G1-2019-08-09.parquet', 'G1-2019-08-20.parquet', 'G1-2019-08-05.parquet', 'G1-2019-08-25.parquet', 'G1-2019-08-26.parquet', 'G1-2019-08-22.parquet', 'G1-2019-08-07.parquet', 'G1-2019-08-16.parquet', 'G1-2019-08-30.parquet', 'G1-2019-08-15.parquet', 'G1-2019-08-19.parquet', 'G1-2019-08-17.parquet', 'G1-2019-08-21.parquet', 'G1-2019-08-04.parquet', 'G1-2019-08-14.parquet', 'G1-2019-08-13.parquet', 'G1-2019-08-24.parquet', 'G1-2019-08-02.parquet', 'G1-2019-08-29.parquet']

In [3]:
all_files.sort()

In [4]:
dataset_analise = []

In [ ]:
for elem in range(0,len(all_files)):
    dfbus = pd.read_parquet('/home/vinicius.vancellote/data/parquet/join/' + all_files[elem],engine='fastparquet')
    df = dfbus.groupby(['data_particao','horario','id_estacao','acumulado_chuva_15_min','acumulado_chuva_1_h','acumulado_chuva_4_h','acumulado_chuva_24_h','acumulado_chuva_96_h'],as_index=False).agg(
        velocidade_inst = pd.NamedAgg(column = 'VELOCITY',aggfunc = 'mean'),
        agitacao_soma = pd.NamedAgg(column = 'DIST',aggfunc='sum'),
        agitacao_media = pd.NamedAgg(column = 'DIST',aggfunc='mean'),
        avgspeed = pd.NamedAgg(column = 'AVGSPEED',aggfunc='mean'),
        qtd_onibus = pd.NamedAgg(column = 'BUSID',aggfunc = 'nunique'),
        qtd_registros = pd.NamedAgg(column = 'BUSID',aggfunc = 'count'),
    )
    dataset_analise.append(df)
    print(all_files[elem])
df_result = pd.concat(dataset_analise,ignore_index=True)

In [ ]:
df_result.to_parquet('/home/vinicius.vancellote/data/BaseAnalise2'+all_files[elem],engine='fastparquet')

In [ ]:
databus=[]
dfbus = []
df_r = []
df2 =[]
limit=0
for elem in range(0,len(all_files)):
    df1 = pd.read_parquet('/home/vinicius.vancellote/data/parquet/join/' + all_files[elem],engine='fastparquet')
    df2.append(df1)
#    df_aux = dfbus.groupby(['data_particao'],as_index=False).agg(
#        qtd_onibus = pd.NamedAgg(column = 'BUSID',aggfunc = 'nunique'),
#        qtd_registros = pd.NamedAgg(column = 'BUSID',aggfunc = 'count'),
#    )
#    databus.append(df_aux)
    print(all_files_ago[elem])
    limit +=1
    if limit == 15:        
        dfbus = pd.concat(df2,ignore_index=True)
        df_qtd_bus = dfbus.groupby(['data_particao'],as_index=False).agg(
            qtd_onibus = pd.NamedAgg(column = 'BUSID',aggfunc = 'nunique'),
            qtd_registros = pd.NamedAgg(column = 'BUSID',aggfunc = 'count'),
        )
        df_r.append(df_qtd_bus)
        dfbus = []
        limit = 0
        print('Break')

In [ ]:
df_r

In [9]:
databus=[]
dfbus = []
for elem in range(0,len(all_files)):
    df1 = pd.read_parquet('/home/vinicius.vancellote/data/parquet/join/' + all_files[elem],engine='fastparquet')
    df1 = df1.sort_values(by=['DATE'],ignore_index=True)
    df_aux = df1.groupby(['data_particao'],as_index=False).agg(
        qtd_onibus = pd.NamedAgg(column = 'BUSID',aggfunc = 'nunique'),
        qtd_registros = pd.NamedAgg(column = 'BUSID',aggfunc = 'count'),
        primeiro_registro = pd.NamedAgg(column = 'DATE',aggfunc = 'first'),
        ultimo_registro = pd.NamedAgg(column = 'DATE',aggfunc = 'last'),
    )
    databus.append(df_aux)
    print(all_files[elem])
#df_qtd_bus2 = dfbus.groupby(['data_particao'],as_index=False).agg(
#    qtd_onibus = pd.NamedAgg(column = 'BUSID',aggfunc = 'nunique'),
#    qtd_registros = pd.NamedAgg(column = 'BUSID',aggfunc = 'count'),
#)

df_qtd_bus = pd.concat(databus,ignore_index=True)

G1-2019-08-01.parquet
G1-2019-08-02.parquet
G1-2019-08-03.parquet
G1-2019-08-04.parquet
G1-2019-08-05.parquet
G1-2019-08-06.parquet
G1-2019-08-07.parquet
G1-2019-08-08.parquet
G1-2019-08-09.parquet
G1-2019-08-10.parquet
G1-2019-08-11.parquet
G1-2019-08-12.parquet
G1-2019-08-13.parquet
G1-2019-08-14.parquet
G1-2019-08-15.parquet
G1-2019-08-16.parquet
G1-2019-08-17.parquet
G1-2019-08-18.parquet
G1-2019-08-19.parquet
G1-2019-08-20.parquet
G1-2019-08-21.parquet
G1-2019-08-22.parquet
G1-2019-08-23.parquet
G1-2019-08-24.parquet
G1-2019-08-25.parquet
G1-2019-08-26.parquet
G1-2019-08-27.parquet
G1-2019-08-28.parquet
G1-2019-08-29.parquet
G1-2019-08-30.parquet
G1-2019-08-31.parquet
G1-2019-12-01.parquet
G1-2019-12-02.parquet
G1-2019-12-03.parquet
G1-2019-12-04.parquet
G1-2019-12-05.parquet
G1-2019-12-06.parquet
G1-2019-12-07.parquet
G1-2019-12-08.parquet
G1-2019-12-09.parquet
G1-2019-12-10.parquet
G1-2019-12-11.parquet
G1-2019-12-12.parquet
G1-2019-12-13.parquet
G1-2019-12-14.parquet
G1-2019-12-15.parquet
G1-2019-12-16.parquet
G1-2019-12-17.parquet
G1-2019-12-18.parquet
G1-2019-12-19.parquet
G1-2019-12-20.parquet
G1-2019-12-21.parquet
G1-2019-12-22.parquet
G1-2019-12-23.parquet
G1-2019-12-24.parquet
G1-2019-12-25.parquet
G1-2019-12-26.parquet
G1-2019-12-27.parquet
G1-2019-12-28.parquet
G1-2019-12-29.parquet
G1-2019-12-30.parquet
G1-2019-12-31.parquet

In [10]:
print(df_qtd_bus)

    data_particao  qtd_onibus  qtd_registros   primeiro_registro  \
0      2019-08-01        5216        4702725 2019-08-01 00:00:01
1      2019-08-02        3547          26161 2019-08-01 23:45:01
2      2019-08-02        5222        4595665 2019-08-02 00:00:01
3      2019-08-03        3526          25450 2019-08-02 23:45:01
4      2019-08-03        5113        3943734 2019-08-03 00:00:01
..            ...         ...            ...                 ...
103    2019-12-27        5023        4052464 2019-12-27 00:00:01
104    2019-12-28        4888        3417606 2019-12-28 00:00:01
105    2019-12-29        4715        2878859 2019-12-29 00:00:01
106    2019-12-30        4971        3704297 2019-12-30 00:00:01
107    2019-12-31        4810        2195629 2019-12-31 00:00:01

        ultimo_registro
0   2019-08-01 23:45:00
1   2019-08-01 23:58:45
2   2019-08-02 23:45:00
3   2019-08-02 23:57:45
4   2019-08-03 23:45:00
..                  ...
103 2019-12-27 22:58:47
104 2019-12-28 22:58:42
105 2019-12-29 22:58:45
106 2019-12-30 22:58:49
107 2019-12-31 22:58:29

[108 rows x 5 columns]

In [ ]:
# 0 Segunda 
# 1 Ter√ßa
# 2 Quarta
# 3 Quinta
# 4 Sexta
# 5 S√°bado
# 6 domingo

df_qtd_bus = df_qtd_bus.sort_values(by=['data_particao'])
df_qtd_bus['dia_semana'] = df_qtd_bus['data_particao'].dt.dayofweek

In [ ]:
df_qtd_bus

In [8]:
df1

,DATE,BUSID,LINE,LAT,LONG,VELOCITY,OBJECTID_left,NOME,REGIAO_ADM,CODBAIRRO,...,Name,primary_key,id_estacao,acumulado_chuva_15_min,acumulado_chuva_1_h,acumulado_chuva_4_h,acumulado_chuva_24_h,acumulado_chuva_96_h,horario,data_particao
index,,,,,,,,,,,,,,,,,,,,,
0,2019-12-31 00:00:01,D53680,397.0,-22.88242,-43.48603,40.0,389.0,Senador Camar√°,BANGU,142,...,Regi√£o 12,12_2019-12-31 00:15:00,12.0,0.0,0.0,0.0,0.0,0.0,00:15:00,2019-12-31
1,2019-12-31 00:00:01,B28629,321.0,-22.91052,-43.17368,16.0,422.0,Centro,CENTRO,005,...,Regi√£o 15,15_2019-12-31 00:15:00,15.0,0.0,0.0,0.0,0.0,0.0,00:15:00,2019-12-31
2,2019-12-31 00:00:01,D86314,867.0,-22.98798,-43.55507,38.0,894.0,Ilha de Guaratiba,GUARATIBA,164,...,Regi√£o 20,20_2019-12-31 00:15:00,20.0,0.0,0.0,0.0,0.0,0.0,00:15:00,2019-12-31
3,2019-12-31 00:00:01,D53604,759.0,-22.93566,-43.65593,0.0,387.0,Santa Cruz,SANTA CRUZ,149,...,Regi√£o 22,22_2019-12-31 00:15:00,22.0,0.0,0.0,0.0,0.0,0.0,00:15:00,2019-12-31
4,2019-12-31 00:00:01,D86263,884.0,-22.89509,-43.533,0.0,405.0,Senador Vasconcelos,CAMPO GRANDE,145,...,Regi√£o 26,26_2019-12-31 00:15:00,26.0,0.0,0.0,0.0,0.0,0.0,00:15:00,2019-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2196180,2019-12-31 22:58:25,A48152,426.0,-22.9465,-43.18179,4.0,455.0,Botafogo,BOTAFOGO,020,...,Regi√£o 31,31_2019-12-31 23:00:00,31.0,0.0,0.0,0.0,0.0,0.0,23:00:00,2019-12-31
2196181,2019-12-31 22:58:25,A48074,415.0,-22.94544,-43.25458,42.0,442.0,Tijuca,TIJUCA,033,...,Regi√£o 33,33_2019-12-31 23:00:00,33.0,0.0,0.0,0.0,0.0,0.0,23:00:00,2019-12-31
2196182,2019-12-31 22:58:26,C82612,363.0,-22.85878,-43.37081,0.0,372.0,Marechal Hermes,MADUREIRA,090,...,Regi√£o 24,24_2019-12-31 23:00:00,24.0,0.0,0.0,0.0,0.0,0.0,23:00:00,2019-12-31
2196183,2019-12-31 22:58:28,B11531,669.0,-22.81113,-43.37296,0.0,337.0,Pavuna,PAVUNA,114,...,Regi√£o 24,24_2019-12-31 23:00:00,24.0,0.0,0.0,0.0,0.0,0.0,23:00:00,2019-12-31
2196184,2019-12-31 22:58:29,B11555,362.0,-22.86634,-43.35512,0.0,379.0,Bento Ribeiro,MADUREIRA,089,...,Regi√£o 10,10_2019-12-31 23:00:00,10.0,0.0,0.0,0.0,0.0,0.0,23:00:00,2019-12-31

In [ ]:
df_qtd_bus.to_parquet('/home/vinicius.vancellote/data/Onibus_Dia',engine='fastparquet')